name: flutter_app
description: "A new Flutter project."
publish_to: 'none'  
version: 0.1.0      

environment:
  sdk: ">=3.5.4 <4.0.0"  # Flutter SDK versiyonu

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8       # iOS stil ikonlar için
  flutter_secure_storage: ^9.2.2 # Güvenli veri depolama için
  go_router: ^14.6.1            # Sayfa yönlendirme (routing) için
  shared_preferences: ^2.3.3     # Basit veri depolama için
  dotlottie_loader: ^0.0.4
  lottie: ^3.2.0
  google_fonts: ^6.2.1
  flutter_localizations:         # Çoklu dil desteği için
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0         # Kod kalitesi kontrolleri için

flutter:
  uses-material-design: true    # Material Design widget'larını kullanmak için
  assets:                       # Projedeki dosya kaynakları
    - assets/images/            # Görseller için
    - assets/icons/             # İkonlar için
    - assets/languages/         # Dil dosyaları için
    - assets/motions/           # Animasyon dosyaları için
    - assets/fonts/             # Font dosyaları için

  fonts:
    - family: Akaya
      fonts:
        - asset: assets/fonts/AkayaKanadaka-Regular.ttf
    - family: Kalam
      fonts:
        - asset: assets/fonts/Kalam-Regular.ttf
